Validate notes

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -28,10 +28,17 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Validate SHA
+        run: git rev-parse --verify ${{ env.LATEST_SHA }} || echo "Invalid SHA. Proceeding without generating notes."
+
       - name: Generate release notes
         run: |
-          NOTES=$(git log --pretty=format:'- %s' $LATEST_SHA..HEAD)
-          echo "NOTES=$NOTES" >> $GITHUB_ENV
+          if git rev-parse --verify $LATEST_SHA > /dev/null 2>&1; then
+            NOTES=$(git log --pretty=format:'- %s' $LATEST_SHA..HEAD)
+            echo "NOTES=$NOTES" >> $GITHUB_ENV
+          else
+            echo "NOTES=No previous release found or invalid SHA. Proceeding without generating notes." >> $GITHUB_ENV
+          fi
 
       - name: Set up JDK 17
         uses: actions/setup-java@v3
